### ISSUE TITLE
Event panel layout

### ISSUE THREAD

**Issue by DPatient** [DeckOfPandas/too-much-of-a-person#175]
- If people don't have Facebook they need to be able to see basic details: location, time, etc Can everyone even if they don't have Facebook click that link and get more information?
- Do we need a button saying Book Story Slam Now that takes you straight to the Kickstarter page?
- If we keep Facebook link justify the events left so it look accumulative :)

**Comment by DPatient** [comment]
Another option is to have the events written out clearly and entered manually with a link to Facebook event but more obvious link to tickets sales

**Comment by DeckOfPandas** [comment]
For ref, the PR with this feature plus staging build URL is #174

**Comment by DeckOfPandas** [comment]
1. You have set the event to "Public", so yes, no fb account required to see it -- here is a screenshot of what you see if you click the link while not logged in to fb:

![screen shot 2018-09-18 at 10 43 58](https://user-images.githubusercontent.com/2399432/45679158-f0a4f680-bb2f-11e8-91a3-c33b1954fa90.png)

**Comment by DeckOfPandas** [comment]
2. Can do if you want

**Comment by DeckOfPandas** [comment]
3. Lol, will do if this remains relevant!

**Comment by DeckOfPandas** [comment]
4. Yes we can def do this, and I've already got templates sorted for it as a startoff (remember wayyyy back to the start I added that in my very first setup). In my opinion, this would look really good too in terms of professionalism. It could be done with Cards or something as per our current styling for lists of blogs posts like here: https://deploy-preview-172--toomuchofaperson.netlify.com/blog/ . Or anything your heart desires.

BUT I didn't do the feature this^^ way for this first draft, as the info for each event would have to be entered manually by someone in the same way as for the Stories. You/someone would need to create a new file here on GitHub, with contents looking something like the block below this message.

If you are happy to do this yourself, the live site would update as necessary when you save the file without anyone needing to do anything else. Obviously I can do this for you in theory (and @EmmaDonaldson totally can if you can persuade her :p), but ultimately me updating the site for you every time you want different content isn't that sustainable -- I will eventually go back to working full time, and will need to schedule time to help with tmoap rather than just updating things almost on the spot as I am doing now.

Ultimately though, I can make this feature however you want. 
[ You know this really, but I'm a total pushover for community goodness and awesome people, so the combination basically guarantees my input limited only by physical capability! ]

```
---
layout: event
publish_this_now: true
title:  "Story Slam"
date:   2018/09/14
cover_image: "2018-oct-story_slam.jpg"
organiser: "Diana Patient" (or "host" or whatever)
location: "Place, Place street, City, AB1 1XX"
gmaps_url: https://...etc
price: free (or "£1.00" or "donations welcome" or whatever)
link_to_book: https://...etc
more_info: https://...etc
---
```

**Comment by DPatient** [comment]
I like this I think it would be more clear and then have a link to Facebook? "something as per our current styling for lists of blogs posts like here: https://deploy-preview-172--toomuchofaperson.netlify.com/blog/ "

If we linked to Facebook would events automatically appear here?

**Comment by DPatient** [comment]
Is it too much trouble to do it this way for now and then change so it updates in a different way later? I think priority is to get the event on the website in whatever form though :)

**Comment by DeckOfPandas** [comment]
On it
...lacb

**Comment by DPatient** [comment]
Big thing: we need people to know that tickets are available on the door!

**Comment by DeckOfPandas** [comment]
https://deploy-preview-195--toomuchofaperson.netlify.com/#index_events

**Comment by DeckOfPandas** [comment]
WIP build in #195

**Comment by DeckOfPandas** [comment]
Deployed to https://toomuchofaperson.com/
